name: bytewords
description: Bytewords implementation in dart
version: 1.0.0
repository: https://git.mrcyjanek.net/mrcyjanek/bytewords
publish_to: https://git.mrcyjanek.net/api/packages/mrcyjanek/pub

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
